services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: champy
      POSTGRES_PASSWORD: AZERTY2005
      POSTGRES_DB: db_food
    ports:
      - "5433:5432" 
  
  web:
    build: .
    depends_on:
      - db
    command: ["python", "run.py"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
