version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://champy:AZERTY2005@db:5432/db_food
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: champy
      POSTGRES_PASSWORD: AZERTY2005
      POSTGRES_DB: db_food
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
