"""empty message

Revision ID: e1c3c148c029
Revises: 45b8de673fa0
Create Date: 2025-06-06 22:56:35.437673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c3c148c029'
down_revision = '45b8de673fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nuriture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('mot_de_passe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mot_de_passe', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('nuriture', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
